apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hCsdA5HNAcu60xo30RD+2goAtRLDbZByEFpfZhmuoJM/yiYARHEEFg==,iv:NKlcGVLIm4pT1elUJykQ1k6js4thZbxeNGoTpwPwNDg=,tag:mek8dKP+HxDYcEy7n/qmvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs54s2kny8erhux5d9m2p26e7qfgru8pke5pwv5zya3cfthnkd9s8uj9xd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYmltVm93bXhWRUt0K05u
            UndTT0pDeHR4WmkrTytGR0NSV0t4Y2JqN0dRCkNTUmRyMzhiTlU5aDZQMlJIbmpl
            emxEY1BzQkVqMjg4ZHhsR1lRdVRhdHMKLS0tIFFMU1NkZThYU2hwV01zZ0wwYmRn
            K3BFYUM3S1JFaDlyN25LcHhCRzUzcWcKS/fhljXW4S4ml/4QtoUisZz6d6cPe70U
            lc3YiDeF7hx+EIpLKtX432ShPMPcMry7MhjjnKwWIBx2xWzTF+aQHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-14T19:08:17Z"
    mac: ENC[AES256_GCM,data:/ZPxS30oD8jmU+m1mL84fEdlr1/pw3AnR2JGKNXjGL1F73XflSiCyv585NV1KLj+NRksGh6QSo6Mn8I/dPKPYSS2tzARfyGdkYGVrzr3hLuNfOfFIlW5ej+y7bD7cz8clQ62NRrwQkUIBZH35C9oMEyY4pcV3SvwQch4g3b+U8Y=,iv:zo51MmXmrlBCQbEbBE7s7UiCXztvYDArRw13n3YDaIg=,tag:V+MdxgHkOdWo93YHIgtBGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
