apiVersion: v1
kind: Secret
metadata:
    name: mongodb-users-admin-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:KnH7Ff4=,iv:nfMxJ7dZjnsnYXHYPrsLQT9+lalLUZ6on6pIb9r6jl8=,tag:IS0wnFI6HtnsZbdN1z1KKQ==,type:str]
    password: ENC[AES256_GCM,data:GFGaheOzjrbMO9YW,iv:nkMbBTDSql2/DMUpKnaZBr4WNp8UZAWsPy7u/NGKAc8=,tag:BYMwJv84wlBPSHRfXeAjJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs54s2kny8erhux5d9m2p26e7qfgru8pke5pwv5zya3cfthnkd9s8uj9xd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcFhxazY4U29xUm1Vam9U
            NWNBYklDcEZoTnZrRWE3WG9zckhCUTBlNHlvCitOR2psU3ZEOWpKUUJlK3ptOU4z
            NXF0VFBKMGhrK1V5NmZ0YVNYdlhFVHMKLS0tIFB6Qm9vNDRJUWl2VitpVmJRaDRF
            ZFVpZmhtYUJOUVBpV2FoV2tzUDZVTGMKwfcWeeZA0v/O/YvoyLozl3Y0euVKl2tz
            GA5nvhmrPlzy6m+Ae3p3eCfihbRzTRbslpDwGrs4RGATsC1tu8fmhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T19:21:59Z"
    mac: ENC[AES256_GCM,data:7AZ2JuveIEJp931EVOvOgNOb5gDRDOdHE37uf9SEPnVb0xPoXZGRpCWUtMce4yubmN3GLroWUgHmIJmK+SULf0Rm+YJX7QCMb0WtzsUzW0UiwO6FCMyV6m2t0vAQQ9ok1BNxLVXUSGjWo5Q53hmOVEOVHkakQkBujPpv9Nu6u80=,iv:PipO6Urc+PtxTUuP+WIEwvuA0Rxc1bn9OGKsHikADSo=,tag:3hKDCdI4bTNv9i38F5U9Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
