---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "172.31.0.254"
  METALLB_LB_RANGE: "172.31.0.2-172.31.0.14"
  METALLB_K8S_GATEWAY_ADDR: "172.31.0.2"
  METALLB_INGRESS_ADDR: "172.31.0.3"
