---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: mongodb-community-operator
    namespace: mongodb
spec:
  interval: 15m
  chart:
    spec:
      chart: community-operator
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    operator:
      watchNamespace: "*"
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 100Mi
    database:
      name: mongodb-database
      namespace: default
